theme: jekyll-theme-cayman
title: Metaheuristic.ai
description: Distributer framework for hyper-parameter optimization and AutoML.
repository: sergmain/metaheuristic
exclude: [.idea, CNAME, Gemfile, Gemfile.lock,how-to.txt]