theme: jekyll-theme-architect
title: STP Baikal
description: Distributer framework for hyper-parameter optimization and AutoML.
repository: sergmain/stp-baikal-411
exclude: [.idea, CNAME, Gemfile, Gemfile.lock,how-to.txt]