theme: jekyll-theme-cayman
title: Metaheuristic.ai
description: Framework for creating custom pipeline such as hyper-parameter optimization, autoML, batch processing and others.
repository: sergmain/metaheuristic
exclude: [.idea, CNAME, Gemfile, Gemfile.lock,how-to.txt]
plugins:
  - jekyll-seo-tag
google_analytics: UA-1592690-18
